export const SET_TOKEN = "SET_TOKEN";
export const SET_USER = "SET_USER";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";

export const SET_USER_ABILITIES = "SET_USER_ABILITIES";

export const SET_LOADING = "SET_LOADING";

export const SET_PRINT_MODE = "SET_PRINT_MODE";

export const SET_VALIDATION_ERRORS = "SET_VALIDATION_ERRORS";
export const CLEAR_VALIDATION_ERRORS = "CLEAR_VALIDATION_ERRORS";

export const SET_PAYMENT_SETTING = "SET_PAYMENT_SETTING";

export const SET_ALERT = "SET_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const NEW_PERMISSION = "NEW_PERMISSION";
export const GET_PERMISSION = "GET_PERMISSION";
export const UPDATE_PERMISSION = "UPDATE_PERMISSION";
export const DELETE_PERMISSION = "DELETE_PERMISSION";
export const DELETE_PERMISSIONS = "DELETE_PERMISSIONS";

export const GET_ROLES = "GET_ROLES";
export const NEW_ROLE = "NEW_ROLE";
export const GET_ROLE = "GET_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_ROLES = "DELETE_ROLES";

export const GET_USERS = "GET_USERS";
export const NEW_USER = "NEW_USER";
export const GET_USER = "GET_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USERS = "DELETE_USERS";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";

export const GET_TANKS = "GET_TANKS";
export const NEW_TANK = "NEW_TANK";
export const GET_TANK = "GET_TANK";
export const UPDATE_TANK = "UPDATE_TANK";
export const DELETE_TANK = "DELETE_TANK";
export const DELETE_TANKS = "DELETE_TANKS";

export const GET_DISPENSERS = "GET_DISPENSERS";
export const NEW_DISPENSER = "NEW_DISPENSER";
export const GET_DISPENSER = "GET_DISPENSER";
export const UPDATE_DISPENSER = "UPDATE_DISPENSER";
export const DELETE_DISPENSER = "DELETE_DISPENSER";
export const DELETE_DISPENSERS = "DELETE_DISPENSERS";

export const GET_METERS = "GET_METERS";
export const GET_DETAILED_METERS = "GET_DETAILED_METERS";
export const NEW_METER = "NEW_METER";
export const GET_METER = "GET_METER";
export const UPDATE_METER = "UPDATE_METER";
export const DELETE_METER = "DELETE_METER";
export const DELETE_METERS = "DELETE_METERS";

export const GET_VEHICLES = "GET_VEHICLES";
export const GET_VEHICLE_CHAMBERS = "GET_VEHICLE_CHAMBERS";
export const NEW_VEHICLE = "NEW_VEHICLE";
export const GET_VEHICLE = "GET_VEHICLE";
export const UPDATE_VEHICLE = "UPDATE_VEHICLE";
export const DELETE_VEHICLE = "DELETE_VEHICLE";
export const DELETE_VEHICLES = "DELETE_VEHICLES";

export const GET_BANKS = "GET_BANKS";
export const NEW_BANK = "NEW_BANK";
export const GET_BANK = "GET_BANK";
export const UPDATE_BANK = "UPDATE_BANK";
export const DELETE_BANK = "DELETE_BANK";
export const DELETE_BANKS = "DELETE_BANKS";

export const GET_PAYMENT = "GET_PAYMENT";
export const GET_PAYMENTS = "GET_PAYMENTS";
export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const PAYMENT = "PAYMENT";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const NEW_TRANSACTION = "NEW_TRANSACTION";
export const OLD_TRANSACTION = "OLD_TRANSACTION";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const DELETE_TRANSACTIONS = "DELETE_TRANSACTIONS";

export const GET_EXPENSE_SOURCES = "GET_EXPENSE_SOURCES";
export const NEW_EXPENSE_SOURCE = "NEW_EXPENSE_SOURCE";
export const OLD_EXPENSE_SOURCE = "OLD_EXPENSE_SOURCE";
export const GET_EXPENSE_SOURCE = "GET_EXPENSE_SOURCE";
export const UPDATE_EXPENSE_SOURCE = "UPDATE_EXPENSE_SOURCE";
export const DELETE_EXPENSE_SOURCE = "DELETE_EXPENSE_SOURCE";
export const DELETE_EXPENSE_SOURCES = "DELETE_EXPENSE_SOURCES";

export const GET_EXPENSES = "GET_EXPENSES";
export const NEW_EXPENSE = "NEW_EXPENSE";
export const OLD_EXPENSE = "OLD_EXPENSE";
export const GET_EXPENSE = "GET_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_EXPENSES = "DELETE_EXPENSES";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const NEW_EMPLOYEE = "NEW_EMPLOYEE";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES";

export const GET_SALARIES = "GET_SALARIES";
export const NEW_SALARY = "NEW_SALARY";
export const GET_SALARY = "GET_SALARY";
export const UPDATE_SALARY = "UPDATE_SALARY";
export const DELETE_SALARY = "DELETE_SALARY";
export const OLD_SALARY = "OLD_SALARY";
export const GET_SALARY_TOTALS = "GET_SALARY_TOTALS";

export const GET_COMPANIES = "GET_COMPANIES";
export const NEW_COMPANY = "NEW_COMPANY";
export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const DELETE_COMPANIES = "DELETE_COMPANIES";

export const GET_PURCHASES = "GET_PURCHASES";
export const NEW_PURCHASE = "NEW_PURCHASE";
export const GET_PURCHASE = "GET_PURCHASE";
export const UPDATE_PURCHASE = "UPDATE_PURCHASE";
export const DELETE_PURCHASE = "DELETE_PURCHASE";
export const DELETE_PURCHASES = "DELETE_PURCHASES";
export const OLD_PURCHASE = "OLD_PURCHASE";

export const GET_SELLS = "GET_SELLS";
export const NEW_SELL = "NEW_SELL";
export const GET_SELL = "GET_SELL";
export const UPDATE_SELL = "UPDATE_SELL";
export const DELETE_SELL = "DELETE_SELL";
export const DELETE_SELLS = "DELETE_SELLS";
export const OLD_SELL = "OLD_SELL";

export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const NEW_CUSTOMER = "NEW_CUSTOMER";
export const OLD_CUSTOMER = "OLD_CUSTOMER";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
export const GET_LEDGER_ENTRIES = "GET_LEDGER_ENTRIES";

export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const NEW_ACCOUNT = "NEW_ACCOUNT";
export const OLD_ACCOUNT = "OLD_ACCOUNT";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNTS = "DELETE_ACCOUNTS";

export const GET_PURCHASE_ITEMS = "GET_PURCHASE_ITEMS";
export const NEW_PURCHASE_ITEM = "NEW_PURCHASE_ITEM";
export const OLD_PURCHASE_ITEM = "OLD_PURCHASE_ITEM";
export const GET_PURCHASE_ITEM = "GET_PURCHASE_ITEM";
export const UPDATE_PURCHASE_ITEM = "UPDATE_PURCHASE_ITEM";
export const DELETE_PURCHASE_ITEM = "DELETE_PURCHASE_ITEM";
export const DELETE_PURCHASE_ITEMS = "DELETE_PURCHASE_ITEMS";

export const GET_INVOICES = "GET_INVOICES";
export const NEW_INVOICE = "NEW_INVOICE";
export const OLD_INVOICE = "OLD_INVOICE";
export const GET_INVOICE = "GET_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_INVOICES = "DELETE_INVOICES";

export const GET_STOCK_ITEMS = "GET_STOCK_ITEMS";
export const NEW_STOCK_ITEM = "NEW_STOCK_ITEM";
export const OLD_STOCK_ITEM = "OLD_STOCK_ITEM";
export const GET_STOCK_ITEM = "GET_STOCK_ITEM";
export const UPDATE_STOCK_ITEM = "UPDATE_STOCK_ITEM";
export const DELETE_STOCK_ITEM = "DELETE_STOCK_ITEM";
export const DELETE_STOCK_ITEMS = "DELETE_STOCK_ITEMS";

export const GET_GATE_PASSES = "GET_GATE_PASSES";
export const GET_SELL_GATE_PASS = "GET_SELL_GATE_PASS";
export const GET_NO_SELL_GATE_PASSES = "GET_NO_SELL_GATE_PASSES";
export const NEW_GATE_PASS = "NEW_GATE_PASS";
export const GET_GATE_PASS = "GET_GATE_PASS";
export const UPDATE_GATE_PASS = "UPDATE_GATE_PASS";
export const DELETE_GATE_PASS = "DELETE_GATE_PASS";
export const DELETE_GATE_PASSES = "DELETE_GATE_PASSES";

export const GET_PRODUCTIONS = "GET_PRODUCTIONS";
export const NEW_PRODUCTION = "NEW_PRODUCTION";
export const GET_PRODUCTION = "GET_PRODUCTION";
export const UPDATE_PRODUCTION = "UPDATE_PRODUCTION";
export const DELETE_PRODUCTION = "DELETE_PRODUCTION";
export const DELETE_PRODUCTIONS = "DELETE_PRODUCTIONS";

export const GET_MACHINES = "GET_MACHINES";
export const NEW_MACHINE = "NEW_MACHINE";
export const GET_MACHINE = "GET_MACHINE";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
export const DELETE_MACHINE = "DELETE_MACHINE";
export const DELETE_MACHINES = "DELETE_MACHINES";

export const GET_BULK_PAYMENTS = "GET_BULK_PAYMENTS";
export const NEW_BULK_PAYMENT = "NEW_BULK_PAYMENT";
export const GET_BULK_PAYMENT = "GET_BULK_PAYMENT";
export const DELETE_BULK_PAYMENT = "DELETE_BULK_PAYMENT";

export const GET_REPORT_DATA = "GET_REPORT_DATA";

export const GET_APP_SETTING = "GET_APP_SETTING";
export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";

export const UPDATE_UNCLEARED_CHEQUES = "UPDATE_UNCLEARED_CHEQUES";
export const UPDATE_ALL_UNCLEARED_CHEQUES = "UPDATE_ALL_UNCLEARED_CHEQUES";
